# READ DATA

In [1]:
import pandas as pd
from pandas import DataFrame
import numpy as np
from numpy.random import seed
import tensorflow as tf
import pickle

data = pd.read_csv('GSE50834_data_set.csv')
data

/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

Unnamed: 0  ILMN_1794187  ILMN_3289262  ILMN_2046024  ILMN_2301955  \
0   GSM1230902     10.228458     12.447313      8.612179      8.673253   
1   GSM1230903     10.656943     12.485980      8.622894      8.493379   
2   GSM1230904     10.517502     12.586375      8.831440      8.735089   
3   GSM1230905     10.265217     12.437653      8.592745      8.704467   
4   GSM1230906     10.371428     12.503396      9.017009      9.008078   
5   GSM1230907     10.455564     12.358937      8.589292      8.367664   
6   GSM1230908     10.360298     12.133589      8.538635      8.760893   
7   GSM1230909     10.611154     12.401528      9.055513      8.794549   
8   GSM1230910     10.335201     12.269144      8.778080      8.857595   
9   GSM1230911     10.423473     12.295987      8.714081      8.796880   
10  GSM1230912      9.898544     12.201487      8.435612      8.482397   
11  GSM1230913     10.007616     11.942643      8.239694      8.549615   
12  GSM1230914     10.074463     12.249567      8.547373      8.772832   
13  GSM1230915     10.215448     12.221149      8.581841      8.378568   
14  GSM1230916     10.475166     12.316494      8.811644      8.752277   
15  GSM1230917     10.669390     12.597792      9.038697      8.786511   
16  GSM1230918     10.125323     12.671156      8.831035      8.606368   
17  GSM1230919     10.499607     12.363480      8.595754      8.687299   
18  GSM1230920     10.347333     12.060395      8.822459      8.342097   
19  GSM1230921     10.212898     12.453564      8.828298      8.567762   
20  GSM1230922     10.057735     12.325342      8.539198      8.686942   
21  GSM1230923      9.988727     12.406678      8.193106      8.801918   
22  GSM1230924     10.590026     12.272119      8.553410      8.822676   
23  GSM1230925      9.904005     11.961772      7.799010      7.865313   
24  GSM1230926      9.308926     11.772735      8.545134      8.735028   
25  GSM1230927      9.576911     12.167622      8.313491      8.357182   
26  GSM1230928     10.235763     11.889185      8.480693      8.517134   
27  GSM1230929      9.595030     12.087871      8.093793      8.051410   
28  GSM1230930      9.737041     11.866143      8.062240      8.170000   
29  GSM1230931      9.719784     11.783911      8.193042      8.091160   
30  GSM1230932      9.864980     12.052945      8.261691      8.163811   
31  GSM1230933      9.470464     11.586980      8.018517      7.982041   
32  GSM1230934      9.770492     11.925031      8.308580      7.991102   
33  GSM1230935     10.105123     12.027861      8.136719      8.090811   
34  GSM1230936     10.270786     12.358920      8.771777      8.845732   
35  GSM1230937      9.965109     11.711116      8.269655      8.376130   
36  GSM1230938      9.605152     11.989746      8.157099      8.512898   
37  GSM1230939      9.288299     11.981339      8.046355      8.051116   
38  GSM1230940      9.891240     12.197432      8.592143      8.362899   
39  GSM1230941      9.690546     11.949360      8.069734      7.929702   
40  GSM1230942      9.197445     11.782785      7.989366      8.104232   
41  GSM1230943      9.923518     12.252092      8.105081      7.947368   
42  GSM1230944     10.114055     11.955639      8.050757      8.180277   
43  GSM1230945      9.733017     12.055425      7.887714      8.304420   

    ILMN_2174296  ILMN_2057826  ILMN_1766718  ILMN_1669966  ILMN_1772658  \
0       8.844207      9.692136      8.556280     11.353527     10.561517   
1       9.326236      9.837946      8.506899     11.412305     10.605563   
2       9.212295      9.766431      8.543384     11.860971     10.771085   
3       8.686311      9.449483      8.371450     11.535392     10.616365   
4       9.211514      9.958543      9.149463     11.404343     11.034545   
5       9.173277      9.823028      8.789312     11.425132     10.696263   
6       9.197445      9.844979      8.696623     11.305344     10.797435   
7       9.265034      9.993533      9.028182     11.383801     10

# CHECKING MISSING VALUE

In [2]:
print('Total Missing Value pada Data HIV:',data.isnull().sum().sum())

Total Missing Value pada Data HIV: 0


In [3]:
dict = {'H': 0, 'HT': 1} 
data.replace(dict, inplace=True)
data = data.drop(['Unnamed: 0'],axis=1)
data.rename({"Type":"Label"}, axis="columns", inplace=True)
data.head()

ILMN_1794187  ILMN_3289262  ILMN_2046024  ILMN_2301955  ILMN_2174296  \
0     10.228458     12.447313      8.612179      8.673253      8.844207   
1     10.656943     12.485980      8.622894      8.493379      9.326236   
2     10.517502     12.586375      8.831440      8.735089      9.212295   
3     10.265217     12.437653      8.592745      8.704467      8.686311   
4     10.371428     12.503396      9.017009      9.008078      9.211514   

   ILMN_2057826  ILMN_1766718  ILMN_1669966  ILMN_1772658  ILMN_2229205  \
0      9.692136      8.556280     11.353527     10.561517      9.018626   
1      9.837946      8.506899     11.412305     10.605563      9.511873   
2      9.766431      8.543384     11.860971     10.771085      9.346407   
3      9.449483      8.371450     11.535392     10.616365      8.944577   
4      9.958543      9.149463     11.404343     11.034545      9.283933   

   ...    ILMN_2348975  ILMN_1803744  ILMN_2077130  ILMN_2067370  \
0  ...        9.636443      9.611193     15.874676     11.874055   
1  ...        9.699864      9.930575     15.765030     11.986276   
2  ...        9.882241      9.939760     15.740516     12.131542   
3  ...        9.753710      9.921771     15.806404     11.870542   
4  ...        9.619543      9.739462     15.871915     12.172971   

   ILMN_1729749  ILMN_2407464  ILMN_2145518  ILMN_1674228  ILMN_1659365  Label  
0     11.845862     10.992577     12.114439      8.659232      8.285046      0  
1     11.913839     11.016613     12.001186      9.117659      8.801269      0  
2     11.934962     11.192669     11.974321      8.666061      9.007683      0  
3     12.795027     10.790674     12.172971      8.975991      9.434714      0  
4     12.519440     11.158452     12.159433      9.355642      9.380926      0  

[5 rows x 15530 columns]

# SPLITTING DATA

In [4]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data, test_size = 0.30, random_state = 5)
test

ILMN_1794187  ILMN_3289262  ILMN_2046024  ILMN_2301955  ILMN_2174296  \
29      9.719784     11.783911      8.193042      8.091160      8.243150   
41      9.923518     12.252092      8.105081      7.947368      8.106736   
25      9.576911     12.167622      8.313491      8.357182      8.065168   
3      10.265217     12.437653      8.592745      8.704467      8.686311   
22     10.590026     12.272119      8.553410      8.822676      9.185886   
26     10.235763     11.889185      8.480693      8.517134      8.680338   
6      10.360298     12.133589      8.538635      8.760893      9.197445   
4      10.371428     12.503396      9.017009      9.008078      9.211514   
37      9.288299     11.981339      8.046355      8.051116      7.972302   
24      9.308926     11.772735      8.545134      8.735028      8.810880   
5      10.455564     12.358937      8.589292      8.367664      9.173277   
0      10.228458     12.447313      8.612179      8.673253      8.844207   
28      9.737041     11.866143      8.062240      8.170000      8.026485   
2      10.517502     12.586375      8.831440      8.735089      9.212295   

    ILMN_2057826  ILMN_1766718  ILMN_1669966  ILMN_1772658  ILMN_2229205  \
29      8.568716      7.621165     12.044739      9.467481      8.207825   
41      9.154474      7.788673     11.588916     10.074141      8.455163   
25      9.092340      8.100247     11.801167     10.055743      8.582029   
3       9.449483      8.371450     11.535392     10.616365      8.944577   
22      9.595550      8.741673     11.539828     10.834345      9.199584   
26      9.204735      8.374448     11.683854     10.312282      9.005838   
6       9.844979      8.696623     11.305344     10.797435      9.418468   
4       9.958543      9.149463     11.404343     11.034545      9.283933   
37      8.823112      7.722719     11.866081     10.036957      8.086571   
24      9.486107      8.493379     11.748411     10.700388      9.010234   
5       9.823028      8.789312     11.425132     10.696263      9.369798   
0       9.692136      8.556280     11.353527     10.561517      9.018626   
28      9.108535      7.759595     11.765750     10.357079      8.826485   
2       9.766431      8.543384     11.860971     10.771085      9.346407   

    ...    ILMN_2348975  ILMN_1803744  ILMN_2077130  ILMN_2067370  \
29  ...        9.681433     10.068886     15.679989     12.018012   
41  ...        9.655692      9.958657     15.698873     12.078695   
25  ...        9.733522      9.965087     15.621723     12.105882   
3   ...        9.753710      9.921771     15.806404     11.870542   
22  ...        9.633170     10.019466     15.874676     11.619349   
26  ...        9.668855     10.128136     15.825560     12.149776   
6   ...        9.451667     10.109961     15.736019     11.818870   
4   ...        9.619543      9.739462     15.871915     12.172971   
37  ...        9.723277     10.183524     15.771322     11.706474   
24  ...        9.777120     10.031481     15.519446     11.763735   
5   ...        9.098619      9.517362     15.621723     11.799172   
0   ...        9.636443      9.611193     15.874676     11.874055   
28  ...        9.504231      9.809693     15.808761     11.914845   
2   ...        9.882241      9.939760     15.740516     12.131542   

    ILMN_1729749  ILMN_2407464  ILMN_2145518  ILMN_1674228  ILMN_1659365  \
29     11.545563     10.870434     11.688753      8.788885      9.715552   
41     11.720625     11.069208     12.039125      8.898964      9.237291   
25     11.904868     11.011982     11.975604      9.365327      8.887687   
3      12.795027     10.790674     12.172971      8.975991      9.434714   
22     11.245784     11.183555     11.882257      8.583997      8.307979   
26     13.071591     10.560075     12.009871      9.083509      9.639039   
6      11.660713     10.726210     11.210312      8.926566      9.278733   
4      12.519440     11.158452     12.159433      9.355642      9.380926   
37

# SAVING DATA TO CSV

In [5]:
train.to_csv('train100%.csv', index=False)
test.to_csv('test100%.csv', index=False)

Read Data

In [6]:
trainwopca = pd.read_csv('train.csv')
testwopca = pd.read_csv('test.csv')

# NORMALIZATION

In [7]:
from sklearn.preprocessing import  MinMaxScaler

scaler = MinMaxScaler()
scaled_train = scaler.fit_transform(trainwopca)
scaled_test = scaler.transform(testwopca)

scaled_train = DataFrame(trainwopca)
scaled_test = DataFrame(testwopca)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [8]:
x_train = trainwopca.drop(['Label'], axis=1)
y_train = trainwopca['Label']

x_test = testwopca.drop(['Label'], axis=1)
y_test = scaled_test['Label']

# MODEL CLASSIFICATION

In [9]:
from sklearn.svm import SVC  
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

seed(8)
tf.random.set_random_seed(8)

# 1. Linear

In [10]:
model_lin = SVC(kernel='linear') 
model_lin.fit(x_train, y_train)

prediction_linear = model_lin.predict(x_train)
print('Confusion matrix from testing data:')
print(confusion_matrix(y_train, prediction_linear))
print('Accuracy Data Train:', accuracy_score(y_train, prediction_linear))

prediction_linear = model_lin.predict(x_test)
print('Confusion matrix from testing data:')
print(confusion_matrix(y_test, prediction_linear))
print('Accuracy Data Test:', accuracy_score(y_test, prediction_linear))

Confusion matrix from testing data:
[[16  0]
 [ 0 14]]
Accuracy Data Train: 1.0
Confusion matrix from testing data:
[[5 2]
 [1 6]]
Accuracy Data Test: 0.7857142857142857


# 2. Poly

In [11]:
model_poly = SVC(kernel='poly') 
model_poly.fit(x_train, y_train) 
   
prediction_poly = model_poly.predict(x_train)
print('Confusion matrix from testing data:')
print(confusion_matrix(y_train, prediction_poly))
print('Accuracy Data Train:', accuracy_score(y_train, prediction_poly))

prediction_poly = model_poly.predict(x_test)
print('Confusion matrix from testing data:')
print(confusion_matrix(y_test, prediction_poly))
print('Accuracy Data Test:', accuracy_score(y_test, prediction_poly))

Confusion matrix from testing data:
[[16  0]
 [ 0 14]]
Accuracy Data Train: 1.0
Confusion matrix from testing data:
[[5 2]
 [1 6]]
Accuracy Data Test: 0.7857142857142857


/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


# 3. RBF

In [12]:
model_rbf = SVC(kernel='rbf') 
model_rbf.fit(x_train, y_train) 

prediction_rbf = model_rbf.predict(x_train)
print('Confusion matrix from testing data:')
print(confusion_matrix(y_train, prediction_rbf))
print('Accuracy Data Train:', accuracy_score(y_train, prediction_rbf))

prediction_rbf = model_rbf.predict(x_test)
print('Confusion matrix from testing data:')
print(confusion_matrix(y_test, prediction_rbf))
print('Accuracy:', accuracy_score(y_test, prediction_rbf))

Confusion matrix from testing data:
[[16  0]
 [ 5  9]]
Accuracy Data Train: 0.8333333333333334
Confusion matrix from testing data:
[[7 0]
 [5 2]]
Accuracy: 0.6428571428571429


/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
